//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class appointment
    {
        public int idAppointment { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [DataType(DataType.DateTime)]
        [DisplayName("Date et Heure")]
        public System.DateTime datHour { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [DisplayName("Sujet")]
        public string subject { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [DisplayName("Courtier")]
        public int idBroker { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [DisplayName("Client")]
        public int idCustomer { get; set; }
    
        public virtual broker broker { get; set; }
        public virtual customer customer { get; set; }
    }
}
