//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.appointments = new HashSet<appointment>();
        }
    
        public int idCustomer { get; set; }

        [StringLength(50)] //limitation à 50 caractères.
        [Required(ErrorMessage = "Champ requis")] //champ requis
        [DisplayName("Nom de famille")] 
        public string lastName { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Champ requis")]
        [DisplayName("Prénom")]
        public string firstName { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "Champ requis")]
        [DisplayName("Adresse mail")]
        [RegularExpression(@"^[\w\.=-]+@[\w\.-]+\.[\w]{2,3}$", ErrorMessage = "Adresse mail non valide")] // regex mail
        public string mail { get; set; }

        [StringLength(10)]
        [Required(ErrorMessage = "Champ requis")]
        [RegularExpression(@"^0[0-9]{9}$", ErrorMessage = "Numéro de télephone non valide")] // regex tél.
        [DisplayName("Numéro de télephone")]
        public string phoneNumber { get; set; }

        [Required(ErrorMessage = "Champ requis")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Budget non valide")] // regex int
        //[Range(0, Int64.MaxValue, ErrorMessage = "<p>Budget non valide</p>")] // meme chose que la regex
        [DisplayName("Budget")]
        public int budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
    }
}
